Repository AmandaStromdahl/algorithms, pull requests merged in 2022-03, with the labels that each got.

#6 doc: issue #5 documentation about initial tests
  algorithms/dp/bitmasking.py
  initial_tests_log.txt
  report.md
  tests/test_dp.py
Labels: documentation

#12 doc: added a list of requirements #7
  report.md
Labels: documentation

#11 Documentation: Wrote a paragraph about the onboarding experience in the…
  report.md
Labels: documentation

#18 doc: issue #17 added the description of the algorithm
  report.md
Labels: documentation

#21 Implementation of the algorithm #10
  algorithms/dp/bitmasking.py
  tests/test_dp.py
Labels: enhancement

#30 feat & refactor: added test for tsp + renamed bitmasking.py #29
  algorithms/dp/__init__.py
  algorithms/dp/bitmasking_cap_assignment.py
  algorithms/dp/bitmasking_tsp.py
  tests/test_dp.py
Labels: enhancement

#39 doc: added an account of the overall experience and included a link t…
  report.md
Labels: documentation

#43 Clean caps algorithm
  algorithms/dp/bitmasking_cap_assignment.py
Labels: documentation

#40 TSP implementation
  algorithms/dp/bitmasking_tsp.py
Labels: enhancement

#46 Update tsp tests
  report.md
  tests/test_dp.py
Labels: bug, documentation

#56 Fix latex elems
  report.md
Labels: bug

#55 Documentation: Added some UML for the control flow of the new code. R…
  ControlFlow.png
  report.md
Labels: documentation

#59 Increase coverage
  report.md
  tests/test_dp.py
Labels: enhancement

#61 Complete test section report
  report.md
Labels: documentation

#68 doc: issue #67 added the missing parameter
  algorithms/dp/bitmasking_cap_assignment.py
Labels: documentation

#60 Documentation: Changed the report slightly and added UML for TSP. #58
  TSP_UML.png
  report.md
Labels: documentation

#72 Added a description of the difficulties we faced in this project. Rel…
  report.md
Labels: documentation

#35 doc: added a basic structure for the 'Effort spent' section #34
  report.md
Labels: documentation
